-- Add Schladming activities from activities.md
-- This migration adds all the activities listed in the activities.md file

INSERT INTO activities (
    id,
    property_id,
    title,
    description,
    image_url,
    activity_type,
    target_guest_types,
    location,
    contact_info,
    operating_hours,
    price_range,
    booking_required,
    booking_url,
    booking_phone,
    is_active,
    display_order,
    activity_labels,
    weather_suitability,
    created_at,
    updated_at
) VALUES 
-- Mirror Lake Trail (Reiteralm)
(
    '101ea9b1-94c9-4ee4-b1b2-42c8dc154f1b',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Mirror Lake Trail (Reiteralm)',
    'Easy, scenic 4.2 km trail (~1 h 40 min) from Preunegg Jet to Spiegelsee & Obersee, famed for Dachstein reflections.',
    null,
    'outdoor',
    '{family,couple}',
    'Reiteralm',
    'Reiteralm Tourist Info',
    'May-Oct',
    '$',
    false,
    'https://www.schladming-dachstein.at/en/regional-and-offerings/tours/From-the-Reiteralm-to-famous-Mirror-Lake_td_370661',
    null,
    true,
    10,
    '{family,chill,hiking}',
    '{clear,partly_cloudy,cloudy}',
    NOW(),
    NOW()
),
-- Complete Lake Circuit
(
    '102ea9b1-94c9-4ee4-b1b2-42c8dc154f1b',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Complete Lake Circuit (Spiegelsee & Untersee)',
    '~5.1 km circuit (~3 h with breaks) covering Spiegelsee, Untersee, Waldsee; ideal scenic loop.',
    null,
    'outdoor',
    '{family,couple}',
    'Reiteralm',
    'Reiteralm Tourist Info',
    'May-Oct',
    '$',
    false,
    'https://365austria.com/en/lake-hike-from-the-reiteralm-to-the-spiegelsee-and-untersee/',
    null,
    true,
    11,
    '{family,chill,hiking}',
    '{clear,partly_cloudy,cloudy}',
    NOW(),
    NOW()
),
-- Gasselhöhe–Spiegelsee–Obersee Panorama
(
    '103ea9b1-94c9-4ee4-b1b2-42c8dc154f1b',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Gasselhöhe–Spiegelsee–Obersee Panorama',
    'Trail from Gasselhöhe hut through forest to Spiegelsee; optional ascent to Rippetegg (2,126 m) via Obersee.',
    null,
    'outdoor',
    '{couple,all_male,all_female}',
    'Reiteralm',
    'Reiteralm Tourist Info',
    'Summer (good weather)',
    '$$',
    false,
    'https://www.outdooractive.com/de/route/wandern/schladming-dachstein/reiteralm-spiegelsee/1507186/',
    null,
    true,
    12,
    '{intense,adventure,hiking}',
    '{clear,partly_cloudy}',
    NOW(),
    NOW()
),
-- Mirror Lake Extended Loop
(
    '104ea9b1-94c9-4ee4-b1b2-42c8dc154f1b',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Mirror Lake Extended Loop',
    'Extended route: return via Untersee (+30 min) or loop via Rippetegg & Gasselhöhe (+2 h).',
    null,
    'outdoor',
    '{couple,all_male,all_female}',
    'Reiteralm',
    'Reiteralm Tourist Info',
    'May-Oct',
    '$$',
    false,
    'https://www.reiteralm.at/de/sommer/wandern/wandertouren/Spiegelsee',
    null,
    true,
    13,
    '{intense,adventure,hiking}',
    '{clear,partly_cloudy,cloudy}',
    NOW(),
    NOW()
),
-- Reiteralm Lake Stroller Loop
(
    '105ea9b1-94c9-4ee4-b1b2-42c8dc154f1b',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Reiteralm Lake Stroller Loop',
    'Easy circular walk from Preunegg Jet around Reiteralm Lake; flat and stroller-friendly.',
    null,
    'outdoor',
    '{family}',
    'Reiteralm',
    'Reiteralm Tourist Info',
    'Summer',
    'FREE',
    false,
    'https://www.schladming-dachstein.at/en/summer/excursion-mountains/reiteralm-summer',
    null,
    true,
    14,
    '{family,chill,easy}',
    '{clear,partly_cloudy,cloudy}',
    NOW(),
    NOW()
),
-- Moaralmsee Alpine Loop
(
    '106ea9b1-94c9-4ee4-b1b2-42c8dc154f1b',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Moaralmsee Alpine Loop',
    'Scenic summit hike over Hauser Kaibling (2,015 m) with panoramic views, descent to turquoise lake via trail 45.',
    null,
    'outdoor',
    '{couple,all_male,all_female,solo}',
    'Hauser Kaibling',
    'Tourist Information',
    'Summer',
    '$$',
    false,
    'https://www.schladming-dachstein.at/en/regional-and-offerings/tours/Hauser-Kaibling-Moaralmsee-Hans-Wodl-Hutte-Steirischer-Bodensee_td_9999946/',
    null,
    true,
    15,
    '{intense,adventure,hiking}',
    '{clear,partly_cloudy}',
    NOW(),
    NOW()
),
-- Schafsinn Circular Trail
(
    '107ea9b1-94c9-4ee4-b1b2-42c8dc154f1b',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Schafsinn Circular Trail',
    'Family loop with barefoot/sheep-themed stations; short stroller (40 min) or full hiker loop (1 h 45 min).',
    null,
    'outdoor',
    '{family}',
    'Hauser Kaibling',
    'Tourist Information',
    'Summer',
    '$',
    false,
    'https://www.schladming-dachstein.at/en/regional-and-offerings/tours/Circular-hiking-trail-sheep-sense-at-Hauser-Kaibling_td_370680',
    null,
    true,
    16,
    '{family,chill,interactive}',
    '{clear,partly_cloudy,cloudy}',
    NOW(),
    NOW()
),
-- Hopsiland Planai
(
    '108ea9b1-94c9-4ee4-b1b2-42c8dc154f1b',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Hopsiland Planai (Playground Trail)',
    'Elevated playground loop with slides, water play, marble runs, lift access — 1.5 km stroller-friendly.',
    null,
    'outdoor',
    '{family}',
    'Planai',
    '+43 3687 81000',
    'Summer',
    '$',
    false,
    'https://www.planai.at/en/summer/hopsiland-planai',
    '+43 3687 81000',
    true,
    17,
    '{family,chill,playground}',
    '{clear,partly_cloudy,cloudy}',
    NOW(),
    NOW()
),
-- Dachstein Skywalk + Ice Palace
(
    '109ea9b1-94c9-4ee4-b1b2-42c8dc154f1b',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Dachstein Skywalk + Ice Palace',
    'Glacier attractions: skywalk, suspension bridge, glass stairway, plus Ice Palace.',
    null,
    'sightseeing',
    '{family,couple,all_male,all_female,solo,business}',
    'Dachstein',
    'Dachstein Tourist Info',
    'Summer (lift dependent)',
    '$$$',
    true,
    'https://www.derdachstein.at/en/dachstein-glacier-world/glacier-experience/suspension-bridge',
    null,
    true,
    18,
    '{intense,adventure,sightseeing}',
    '{clear,partly_cloudy,cloudy}',
    NOW(),
    NOW()
),
-- Rittisberg Coaster
(
    '110ea9b1-94c9-4ee4-b1b2-42c8dc154f1b',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Rittisberg Coaster (Summer Toboggan)',
    '1.3 km alpine coaster with spirals and banked turns; operates in sun or rain.',
    null,
    'entertainment',
    '{family,couple}',
    'Ramsau',
    'Rittisberg Info',
    'Summer',
    '$$',
    false,
    'https://www.schladming-dachstein.at/en/service/infos-from-a-z/Rittisberg-Coaster-summer-toboggan-run_az_342185',
    null,
    true,
    19,
    '{family,chill,fun}',
    '{clear,cloudy,rain}',
    NOW(),
    NOW()
),
-- Erlebnisbad Schladming
(
    '111ea9b1-94c9-4ee4-b1b2-42c8dc154f1b',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Erlebnisbad Schladming',
    'Indoor pool with 66 m slide, kids area, sauna & fitness—perfect for rainy days.',
    null,
    'wellness',
    '{family,couple}',
    'Schladming',
    'Erlebnisbad Info',
    'All year',
    '$$',
    false,
    'https://erlebnisbad-schladming.at/',
    null,
    true,
    20,
    '{family,indoor,wellness}',
    '{rain,snow,cloudy,clear}',
    NOW(),
    NOW()
),
-- Therme Amadé
(
    '112ea9b1-94c9-4ee4-b1b2-42c8dc154f1b',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Therme Amadé (Altenmarkt)',
    'Spa & water world with slides (incl. loop), pools & saunas; open 09:00–22:00.',
    null,
    'wellness',
    '{family,couple,all_female}',
    'Altenmarkt',
    'Therme Amadé',
    '09:00-22:00',
    '$$',
    true,
    'https://www.thermeamade.at/en/',
    null,
    true,
    21,
    '{family,indoor,wellness,spa}',
    '{rain,snow,cloudy,clear}',
    NOW(),
    NOW()
),
-- Adventure Park Gröbming
(
    '113ea9b1-94c9-4ee4-b1b2-42c8dc154f1b',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Adventure Park Gröbming',
    'Forest high-rope park: 18–22 courses, 200+ stations—great for families/groups.',
    null,
    'adventure',
    '{family,couple,all_male,all_female}',
    'Gröbming',
    'Adventure Park Info',
    'Summer',
    '$$',
    true,
    'https://www.abenteuerpark.at/',
    null,
    true,
    22,
    '{intense,adventure,group}',
    '{clear,partly_cloudy}',
    NOW(),
    NOW()
),
-- Zipline Stoderzinken
(
    '114ea9b1-94c9-4ee4-b1b2-42c8dc154f1b',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Zipline Stoderzinken',
    'Europe''s mega zipline: 2.5 km, ~115 km/h, four parallel lines—adrenaline rush.',
    null,
    'adventure',
    '{couple,all_male,all_female}',
    'Gröbming',
    'Zipline Info',
    'Summer',
    '$$$',
    true,
    'https://www.zipline.at/en',
    null,
    true,
    23,
    '{intense,adventure,adrenaline}',
    '{clear,partly_cloudy}',
    NOW(),
    NOW()
),
-- Tandem Paragliding
(
    '115ea9b1-94c9-4ee4-b1b2-42c8dc154f1b',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Tandem Paragliding',
    'Soar over Schladming with certified pilots.',
    null,
    'adventure',
    '{couple,all_male,all_female,solo}',
    'Planai/Hochwurzen',
    '+43 3687 81000',
    'Summer (weather dependent)',
    '$$$',
    true,
    'https://www.planai.at/en/summer/paragliding',
    '+43 3687 81000',
    true,
    24,
    '{intense,adventure,aerial}',
    '{clear,partly_cloudy}',
    NOW(),
    NOW()
),
-- Enns Bike Path
(
    '116ea9b1-94c9-4ee4-b1b2-42c8dc154f1b',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Enns Bike Path',
    'Scenic river bike path with easy family sections through valleys & lakes.',
    null,
    'outdoor',
    '{family,couple,solo}',
    'Enns Valley',
    'Tourist Information',
    'Summer',
    'FREE',
    false,
    'https://www.schladming-dachstein.at/en/summer/biking/enns-bike-path',
    null,
    true,
    25,
    '{family,chill,biking}',
    '{clear,partly_cloudy,cloudy}',
    NOW(),
    NOW()
),
-- Rafting on the Enns
(
    '117ea9b1-94c9-4ee4-b1b2-42c8dc154f1b',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Rafting on the Enns',
    'Beginner-friendly white-water rafting with local guides.',
    null,
    'adventure',
    '{couple,all_male,all_female,family}',
    'Enns',
    'AOS Adventure',
    'Summer',
    '$$',
    true,
    'https://www.rafting.at/en.html',
    null,
    true,
    26,
    '{intense,adventure,water}',
    '{clear,partly_cloudy}',
    NOW(),
    NOW()
),
-- Schladming Brewery Tour
(
    '118ea9b1-94c9-4ee4-b1b2-42c8dc154f1b',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Schladming Brewery Tour',
    'Local "green" brewery—visit shop or tasting, great on rainy days.',
    null,
    'entertainment',
    '{couple,all_male,all_female}',
    'Schladming',
    'Schladminger Brauerei',
    'All year',
    '$',
    false,
    'https://www.schladmingerbier.at/',
    null,
    true,
    27,
    '{chill,indoor,tasting}',
    '{rain,snow,cloudy,clear}',
    NOW(),
    NOW()
),
-- Golfclub Schladming-Dachstein
(
    '119ea9b1-94c9-4ee4-b1b2-42c8dc154f1b',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Golfclub Schladming-Dachstein',
    '18-hole "Pebble Beach of the Alps", picturesque and challenging.',
    null,
    'recreation',
    '{couple,all_male,all_female,business,solo}',
    'Haus im Ennstal',
    'Golf Club Info',
    'Summer',
    '$$$',
    true,
    'https://www.schladming-golf.at/en/home/',
    null,
    true,
    28,
    '{chill,sport,golf}',
    '{clear,partly_cloudy}',
    NOW(),
    NOW()
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    booking_url = EXCLUDED.booking_url,
    updated_at = NOW();