-- Sample data for vacation rental hospitality system

-- Insert a sample property
INSERT INTO properties (
    id, 
    name, 
    address, 
    wifi_ssid, 
    wifi_password, 
    welcome_message, 
    house_rules, 
    emergency_contact, 
    checkout_instructions,
    created_at,
    updated_at
) VALUES (
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Alpine Chalet Schladming',
    'Bergstraße 123, 8970 Schladming, Austria',
    'ChaletWiFi',
    'Austria2025!',
    'Welcome to our beautiful Alpine Chalet! Enjoy your stay in the heart of Schladming.',
    'No smoking indoors. Quiet hours: 22:00-08:00. Please respect our neighbors.',
    '+43 664 1234567',
    'Please clean dishes, take out trash, and leave keys in the lockbox.',
    NOW(),
    NOW()
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    updated_at = NOW();

-- Insert sample activities
INSERT INTO activities (
    id,
    property_id,
    title,
    description,
    image_url,
    activity_type,
    target_guest_types,
    location,
    contact_info,
    operating_hours,
    price_range,
    booking_required,
    booking_url,
    booking_phone,
    is_active,
    display_order,
    activity_labels,
    weather_suitability,
    created_at,
    updated_at
) VALUES 
(
    '11111111-1111-1111-1111-111111111111',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Planai Skiing',
    'Experience world-class skiing on the Planai mountain, home of the famous night slalom.',
    '/uploads/planai-skiing.jpg',
    'outdoor',
    '{family,couple}',
    'Planai-Hochwurzen, Schladming',
    '+43 3687 81000',
    '08:30-16:00',
    '$$$',
    true,
    'https://www.planai.at',
    '+43 3687 81000',
    true,
    1,
    '{intense,winter,outdoor}',
    '{snow,clear,cloudy}',
    NOW(),
    NOW()
),
(
    '22222222-2222-2222-2222-222222222222',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Dachstein Glacier Tour',
    'Visit the spectacular Dachstein Glacier with ice palace and suspension bridge.',
    '/uploads/dachstein-glacier.jpg',
    'outdoor',
    '{family,couple,solo,business}',
    'Dachstein Gletscher, Ramsau am Dachstein',
    '+43 3687 81000',
    '09:00-16:30',
    '$$',
    false,
    'https://www.dachstein-salzkammergut.at',
    '+43 3687 81000',
    true,
    2,
    '{sightseeing,adventure,glacier}',
    '{clear,cloudy,partly_cloudy}',
    NOW(),
    NOW()
),
(
    '33333333-3333-3333-3333-333333333333',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Schladming Spa Relaxation',
    'Unwind at the luxurious Amadé Spa with thermal pools and wellness treatments.',
    '/uploads/spa-relaxation.jpg',
    'wellness',
    '{couple,family}',
    'Amadé Spa, Schladming',
    '+43 3687 23000',
    '09:00-21:00',
    '$$',
    true,
    'https://www.amade-spa.at',
    '+43 3687 23000',
    true,
    3,
    '{chill,wellness,relaxation}',
    '{rain,snow,cloudy,clear}',
    NOW(),
    NOW()
),
(
    '44444444-4444-4444-4444-444444444444',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Traditional Austrian Dining',
    'Enjoy authentic Austrian cuisine at Gasthof Zur Alten Post.',
    '/uploads/austrian-dining.jpg',
    'restaurant',
    '{family,couple}',
    'Gasthof Zur Alten Post, Schladming',
    '+43 3687 22470',
    '11:30-22:00',
    '$$',
    true,
    'https://www.gasthof-schladming.at',
    '+43 3687 22470',
    true,
    4,
    '{dining,traditional,family}',
    '{rain,snow,cloudy,clear,partly_cloudy}',
    NOW(),
    NOW()
),
(
    '55555555-5555-5555-5555-555555555555',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Hiking Rohrmoos Plateau',
    'Beautiful hiking trails on the Rohrmoos Plateau with stunning mountain views.',
    '/uploads/rohrmoos-hiking.jpg',
    'outdoor',
    '{family,couple,solo}',
    'Rohrmoos Plateau, Schladming',
    'Tourist Information +43 3687 23310',
    '07:00-19:00',
    'FREE',
    false,
    null,
    null,
    true,
    5,
    '{hiking,nature,chill}',
    '{clear,partly_cloudy,cloudy}',
    NOW(),
    NOW()
) ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    updated_at = NOW();

-- Insert sample streaming services
INSERT INTO streaming_services (
    id,
    property_id,
    service_name,
    service_type,
    app_url_scheme,
    logo_url,
    instructions,
    requires_login,
    is_active,
    display_order,
    created_at,
    updated_at
) VALUES 
(
    '11111111-1111-1111-1111-111111111111',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Netflix',
    'video',
    'nflx',
    '/uploads/netflix-logo.png',
    'Launch Netflix app and sign in with your account',
    true,
    true,
    1,
    NOW(),
    NOW()
),
(
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Disney+',
    'video',
    'disneyplus',
    '/uploads/disney-logo.png',
    'Open Disney+ and enjoy family-friendly content',
    true,
    true,
    2,
    NOW(),
    NOW()
),
(
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Prime Video',
    'video',
    'aiv',
    '/uploads/prime-logo.png',
    'Access Amazon Prime Video with your Prime account',
    true,
    true,
    3,
    NOW(),
    NOW()
) ON CONFLICT (id) DO UPDATE SET
    service_name = EXCLUDED.service_name,
    updated_at = NOW();

-- Insert sample guests
INSERT INTO guests (
    id,
    property_id,
    first_name,
    last_name,
    email,
    phone,
    guest_type,
    guest_labels,
    party_size,
    check_in_date,
    check_out_date,
    special_requests,
    notes,
    is_active,
    created_at,
    updated_at
) VALUES 
(
    '7B44CC66-DDD1-400D-863A-52A42A1B8A12',
    '24ea9b80-94c9-4ee4-b1b2-42c8dc154f1b',
    'Hans',
    'Mueller',
    'hans.mueller@email.com',
    '+43 664 9876543',
    'family',
    '{family,outdoor}',
    4,
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '3 days',
    'Late arrival expected',
    'Returning guest, prefers ground floor rooms',
    true,
    NOW(),
    NOW()
) ON CONFLICT (id) DO UPDATE SET
    first_name = EXCLUDED.first_name,
    updated_at = NOW();